### ISSUE TITLE
Only works in English locale.

### ISSUE THREAD

**Issue by skx** [strugee/filter-other-days#17]
Assuming you have Finnish locales installed (you can check with "`locale -a`") you'll find that the month-names are different - something true for many other locales too, such as German ones.

For example I see this on my personal system:

      helsinki ~ $ date +"%b %B"
      tammi tammikuu
 
      helsinki ~ $  LC_ALL=en_US.utf8 date +"%b %B"
      Jan January

You should avoid hard-wiring the names of the months, in either long or short forms, to avoid this.  Also note that the short-form of month days does are necessarily the first three letters of the long name.

**Comment by strugee** [comment]
Hey, so sorry I completely forgot about this ticket!

This is definitely something I'd be interested in fixing. I may get around to it eventually but if anyone wants to work on this, I would love to merge a Pull Request that does the following:

1. Builds month names from whatever locales are present on the user's system
2. Implements a test suite for this. Probably you'll want to have a "basic" test suite that uses the English locales and runs by default and a "full" test suite that requires several locales and runs in CI

I am honestly not sure how to get this information out of the system locale. Now that I think about it I guess we could ship some static files with locale information? But that seems unideal. I'd really prefer to use the system locales.

> Also note that the short-form of month days does are necessarily the first three letters of the long name.

Is there a good way to determine whether this will be the case? Can you get this information out of the system locales? If not, I guess we should just hardcode behavior for different locales...?

**Comment by strugee** [comment]
Just as an FYI, there's work-in-progress code for this in #25.

**Comment by strugee** [comment]
The code for this is still something I'd like to finish up and land.

**Comment by strugee** [comment]
For those following along at home, I just provided an update on this in https://github.com/strugee/filter-other-days/pull/25#issuecomment-489376690. tl;dr this is now blocked on a FreeBSD bug. We will probably work around the bug but I'm waiting to hear back from the FreeBSD folks.

**Comment by strugee** [comment]
FYI, this has been out for a bit in filter-other-days 2.0.0! See https://strugee.net/blog/2019/12/filter-other-days-1.1.0-and-2.0.0-are-now-available
